🚚 change location of tagged directory

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -36,18 +36,22 @@ local_filepath="${backups_dir}/${DB}-${datestamp}.sql.gz"
 if [ ! -f "$local_filepath" ]; then
     # download ArchivesSpace backup from S3
     s3path="s3://${BUCKET}/${DB}-${datestamp}.sql.gz"
-    if ! /usr/local/bin/aws s3 cp "$s3path" "$tmp_dir" --no-progress; then
+    if ! /usr/local/bin/aws s3 cp "$s3path" "$backups_dir" --no-progress; then
         echo "😵 FAILED TO DOWNLOAD BACKUP DATABASE FROM S3."
         exit 1
     fi
-    # decompress the file
-    gunzip -k "${tmp_dir}/${DB}-${datestamp}.sql.gz"
 fi
+
+# decompress the file
+gunzip -k "$local_filepath"
 
 # restore the database from the backup
 if [[ "$1" != "--upgrade" ]]; then
-    docker exec mysql mysql -uas -pas123 archivesspace < "${tmp_dir}/${DB}-${datestamp}.sql"
+    docker exec mysql mysql -uas -pas123 archivesspace < "${backups_dir}/${DB}-${datestamp}.sql"
 fi
+
+# clean up the uncompressed sql file
+rm -f "${backups_dir}/${DB}-${datestamp}.sql"
 
 # change the admin password
 docker exec archivesspace /archivesspace/scripts/password-reset.sh admin admin
@@ -55,7 +59,3 @@ docker exec archivesspace /archivesspace/scripts/password-reset.sh admin admin
 # soft reindex
 docker exec archivesspace rm -f /archivesspace/data/indexer_state/*
 docker exec archivesspace rm -f /archivesspace/data/indexer_pui_state/*
-
-# store the compressed backup db
-cp "${tmp_dir}/${DB}-${datestamp}.sql.gz" "$local_filepath"
-rm -f "${tmp_dir}/${DB}-${datestamp}.sql*"
